######################################################################
# Automatically generated by qmake (2.01a) Thu May 26 16:49:40 2011
######################################################################

TEMPLATE = app
TARGET = PiCalcThreaded
DEPENDPATH += .
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += FormMain.h PiCalcThread.h
SOURCES += FormMain.cpp main.cpp PiCalcThread.cpp
