######################################################################
# Automatically generated by qmake (2.01a) Thu May 26 16:21:51 2011
######################################################################

TEMPLATE = app
TARGET = PiCalc
DEPENDPATH += .
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += FormMain.h
SOURCES += FormMain.cpp main.cpp
